#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
import os
import sys

# Load our support module
sys.path.append(os.path.dirname(__file__))
import utils.cmdline
import plugins

cmd_modules = {
    "cmd_verify",
    "cmd_setup",
    "cmd_update",
    "cmd_upload",
}

if __name__ == "__main__":
    utils.cmdline.main(cmd_modules, plugins)
