# Branches without -f push
[no_force]
# remote : [(local branch, remote branch)]
origin =  [ ["master", "master"]]
ver = [["master", "master"]]
ml = [["master", "master"], ["mlx5-next", "mlx5-next"]]
rdma = [["wip/leon-for-next", "wip/leon-for-next"],
          ["wip/leon-for-rc", "wip/leon-for-rc"]]

# Branches with -f push
[force]
# remote : [(local branch, remote branch)]
origin = [["rdma-next", "rdma-next"],
	  ["rdma-rc", "rdma-rc"],
         ["xfrm-next", "xfrm-next"]]

[testing]
# remote : [(local branch, remote branch)]
ver = [["testing/rdma-next", "testing/rdma-next"],
         ["testing/rdma-rc", "testing/rdma-rc"],
         ["queue-next", "queue-next"],
         ["queue-rc", "queue-rc"]]

# Cross check to see if local branch has updated remote branch
[cross_check]
# remote : [(local branch, remote branch)]
ver = [["queue-next", "testing/net-next"],
         ["queue-next", "testing/net-rc"],
         ["queue-rc", "testing/net-rc"]]
