#!/bin/bash
USER=`whoami`
SRC="/w"

sudo dnf install rsync dwarves ccache cronie -y
sudo rm -rf $SRC

sudo mkdir -p $SRC
sudo chown -R $USER:mtl $SRC/

git clone /swgwork/$USER/src/rdma-core $SRC/rdma-core

git clone /swgwork/$USER/src/kernel $SRC/kernel
cp /.autodirect/l/upstream/common_new/kernels/latest-for-upstream-debug/CONFIGS/config.x86_64.debug $SRC/kernel/.config

TMPFILE=$(mktemp)
cat <<EOF > $TMPFILE
CONFIG_SUNRPC=n
CONFIG_SUNRPC_GSS=n
CONFIG_SUNRPC_BACKCHANNEL=n
CONFIG_SUNRPC_XPRT_RDMA=n
CONFIG_RDS=n
CONFIG_RDS_RDMA=n
CONFIG_OPENVSWITCH=n
CONFIG_OPENVSWITCH_GRE=n
CONFIG_OPENVSWITCH_VXLAN=n
CONFIG_OPENVSWITCH_GENEVE=n
CONFIG_NET_NSH=n
CONFIG_NETDEVSIM=n
EOF
$SRC/kernel/scripts/kconfig/merge_config.sh -y -m $SRC/kernel/.config $TMPFILE
rm -rf $TMPFILE

cp -r /swgwork/$USER/ccache /w
sudo systemctl enable crond
sudo systemctl start crond

TMPFILE=$(mktemp)
echo '#!/usr/bin/sh' > $TMPFILE
echo "sudo -u "$USER" cp -a /w/ccache/? /swgwork/"$USER"/ccache" >> $TMPFILE
echo "sudo -u "$USER" cp -a /swgwork/"$USER"/ccache/? /w/ccache" >> $TMPFILE
sudo -u leonro cp -a /swgwork/leonro/ccache/? /w/ccache

sudo cp $TMPFILE /etc/cron.daily/ccache-sync
sudo chmod a+x /etc/cron.daily/ccache-sync
rm -rf $TMPFILE
