#!/bin/bash
USER=`whoami`
SRC="/w"

sudo dnf install rsync dwarves ccache cronie -y
sudo rm -rf $SRC

sudo mkdir -p $SRC
sudo chown -R $USER:mtl $SRC/

git clone /swgwork/$USER/src/rdma-core $SRC/rdma-core

git clone /swgwork/$USER/src/kernel $SRC/kernel
cp /.autodirect/l/upstream/common_new/kernels/latest-for-upstream-debug/CONFIGS/config.x86_64.debug $SRC/kernel/.config
#less /proc/config.gz > $SRC/kernel/.config

cp -r /swgwork/$USER/ccache /w
sudo systemctl enable crond
sudo systemctl start crond

TMPFILE=$(mktemp)
echo '#!/usr/bin/sh' > $TMPFILE
echo 'sudo -u '$USER' rsync -am --inplace /w/ccache /swgwork/'$USER'' >> $TMPFILE
sudo cp $TMPFILE /etc/cron.daily/ccache-sync
sudo chmod a+x /etc/cron.daily/ccache-sync
rm -rf $TMPFILE
