#!/bin/bash
USER=`whoami`
SRC="/w"

sudo dnf install rsync dwarves ccache cronie -y
sudo rm -rf $SRC

sudo mkdir -p $SRC
sudo chown -R $USER:mtl $SRC/

git clone /swgwork/$USER/src/rdma-core $SRC/rdma-core

git clone /swgwork/$USER/src/kernel $SRC/kernel
#cp /.autodirect/l/upstream/common_new/kernels/latest-for-upstream-debug/CONFIGS/config.x86_64.debug $SRC/kernel/.config
gunzip -d /proc/config.gz -c > $SRC/kernel/.config

mkdir /w/ccache
sudo systemctl enable crond
sudo systemctl start crond

TMPFILE=$(mktemp)
echo 'vm.nr_hugepages = 2' > $TMPFILE
sudo cp $TMPFILE /etc/sysctl.d/60-yo.conf
sudo chmod a+r /etc/sysctl.d/60-yo.conf

rm -rf $TMPFILE
