#!/bin/bash
USER=`whoami`

SRC="/w"

export CCACHE_DIR=$SRC/ccache
cd $SRC/kernel
git checkout -f $_BRANCH

if [ "$_CLEAN" == "True" ]; then
	sudo make clean
fi

make -s olddefconfig -j 64
echo "Started silent compilation"
make -s -j 64
sudo make modules_install install
if [ "$_WITH_H" == "True" ]; then
	sudo make headers_install
fi
sudo grubby --set-default $(ls -t -1 /boot/vmlinuz-* | head -1)
sudo reboot
